name: deepconvlstm
dataset_name: wear
devices: ['cuda:0']
anno_json: [
  'data/wear/annotations/60fps/wear_test_split_1.json',
  'data/wear/annotations/60fps/wear_test_split_2.json',
  'data/wear/annotations/60fps/wear_test_split_3.json',
  'data/wear/annotations/60fps/wear_test_split_4.json',
  'data/wear/annotations/60fps/wear_test_split_5.json',
  'data/wear/annotations/60fps/wear_test_split_6.json',
]
dataset: {
  sens_folder: ./data/wear/raw/inertial/50hz,
  input_dim: 12,
  sampling_rate: 50,
  window_size: 100,
  window_overlap: 50,
  tiou_thresholds: [0.3, 0.4, 0.5, 0.6, 0.7]
}
model: {
  conv_kernels: 64,
  conv_kernel_size: 21,
  lstm_units: 1024,
  lstm_layers: 1,
  dropout: 0.5
}
train_cfg: {
  lr: 0.0001,
  lr_decay: 0.9,
  lr_step: 10,
  epochs: 100,
  weight_decay: 0.000001,
  weight_init: 'xavier_normal',
  weighted_loss: True,
}
loader: {
  batch_size: 100,
}